### ISSUE TITLE
ERG Widget "Ammonia, anhydrous" throws a GP service error.

### ISSUE THREAD

**Issue by csmoore** [Esri/defense-solutions-proofs-of-concept#1]
_From @kgonzago on August 28, 2017 18:34_

### Widget
ERG

### Version of widget
2.0

### Bug or Enhancement
BUG

### Repo Steps or Enhancement details
Use "AMMONIA" for "Large" spills and the GP service returns "ERG Geoprocessing status: Failed".

_Copied from original issue: Esri/solutions-webappbuilder-widgets#961_

**Comment by Dbarnes1** [comment]
https://github.com/ArcGIS/solutions-erg-widget/issues/4
